### ISSUE TITLE
Alt-Tab broken with GNOME Shell 3.32.0

### ISSUE THREAD

**Issue by alexisLefebvre** [christopher-l/instant-switcher-popups#3]
I upgraded Ubuntu to 19.04 and this extension doesn't work anymore and Alt-Tab doesn't respond until I disable this extension.

I use GNOME Shell 3.32.0.

**Comment by corebots** [comment]
Update for 3.32 would be great indeed. Used the extension on previous version of gnome and it was perfect, now it's broken unfortunately.

**Comment by christopher-l** [comment]
I hope this is fixed with https://github.com/christopher-l/instant-switcher-popups/commit/ddbbb2b4bd53f32c74e70dcede886dc2c6813b2c (currently pending review)
